apiVersion: v1
kind: PersistentVolume
metadata: 
  name: host-pv
spec: #################### PERSISTENT VOLUME SPECIFICATIONS
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem # Filesystem, Block
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce" # ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate